spring.application.name=CafeAromaAPI

# Configuracion local privada opcional
spring.config.import=optional:file:./application-local.properties

# Base de datos
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/cafe_aroma}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=${SERVER_PORT:8080}

# JWT
app.jwt.secret=${JWT_SECRET:}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}